Vagrant.configure(2) do |config|
  config.vm.box = "box-cutter/ubuntu1404-desktop"
   config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.name = "Dashboards"
     vb.memory = "2048"
     vb.customize ["modifyvm", :id, "--usb", "off"]
     vb.customize ["modifyvm", :id, "--usbehci", "off"]
   end

   config.vm.provision "shell", inline: <<-SHELL
	sudo apt-get update
	sudo apt-get install -y apache2
	sudo apt-get install -y git
	sudo mkdir /home/vagrant/Dash
	sudo git clone https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-DASHboards.git
	cp -r /home/vagrant/ICSE-2014-DASHboards/* /var/www/html/
	sudo apt-get install -y python
	sudo apt-get install -y python-pip
	sudo pip install pytz
	sudo a2enmod cgi
	cp /vagrant/apache.conf /etc/apache2/
	cp /vagrant/settings.json /var/www/html/cgi-bin/
	chmod -R 777 /vagrant
	chmod -R 777 /home/vagrant
	chmod -R 777 /var/www/html/
	sudo service apache2 restart 

	gsettings set com.canonical.Unity.Launcher favorites "['application://ubiquity.desktop', 'application://nautilus.desktop', 'application://unity-control-center.desktop', 'unity://running-apps', 'application://firefox.desktop' ,'unity://expo-icon', 'unity://devices']"
	
#vagrant ALL=(ALL) NOPASSWD: ALL
   SHELL

#wget http://download.jetbrains.com/idea/ideaIC-13.0.4.tar.gz



end
